source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.4'

workspace 'myTargetDemo'

target :myTargetDemo do

  project 'myTargetDemo.xcodeproj'
  pod 'myTargetSDK', '>= 5.22.0'


































end
