source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

workspace 'myTargetDemo'

target :myTargetDemo do

  project 'myTargetDemo.xcodeproj'
  pod 'myTargetSDK', '>= 5.11.2'










end
